server:
  port: 8800
  servlet:
    # 应用的访问路径
    context-path: /shiyi

spring:
  application:
    name: shiyiblog
  datasource:
    url: ENC(dIi9ZKOtVRnM9PDYIHcFjuHy8EdeSjPt+xDxBKALhtof+YdXXOTwCnr1EKPk8bKSGUeextjahBsYTdt2pbWToXEK1tl5RshwshLkza7tbf0gP0An6SAx0c9PIvxolwJ+rkectARkQ2flm05+NepDJXj/ik3OPCG3Oz+NAml/VrFhW+2ZBNcLofOFAmD6umnXPXJ62S6eOg8=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(BJIOzH0JBEm92VwQds59Iw==)
    type: com.alibaba.druid.pool.DruidDataSource
  elasticsearch:
    rest:
      uris: localhost:9200
  redis:
    host: 42.192.150.44
    port: 6379
    timeout: 3000
    password: ENC(BJIOzH0JBEm92VwQds59Iw==)

jasypt:
  encryptor:
    password: RequiredEncryptionconfigurationpropertymissing
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.shiyi.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 0
      #logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  logging:
    level: warn
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  secret: shiyi2021
  # 令牌过期时间 此处单位/毫秒 四个小时
  expiration: 3600000
zw:
  swagger:
    title: 拾壹博客项目接口文档
    description: 拾壹博客项目接口文档
    version: 1.0.0
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:
  #安全认证
  auth:
    # token过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 5
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 1
    ignoreUrls:
      - /login
      - /swagger-ui.html
      #      - /swagger-resources/**
      - /swagger-resources/configuration/ui
      - /swagger-resources
      - /v2/api-docs
      - /swagger-resources/configuration/security
      #      - /swagger/**
      #      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
#第三方配置信息
qq:
  app-id: 101995894
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}
weibo:
  app-id: 2285022919
  app-secret: a380fef0743e38cad12125902b204fab
  grant-type: authorization_code
  redirect-url: http://www.shiyit.com/callback/weibo
  access-token-url: https://api.weibo.com/oauth2/access_token
  user-info-url: https://api.weibo.com/2/users/show.json?uid={uid}&access_token={access_token}
gitee:
  app-id: d029020a6839273e0e82d853783874bf1f4f34b95da6ebcbc230e6603ff9b656
  app-secret: e94dfa5baaa5ac896bd01d077d742020504910a0a4c974a83d40d51a0d8377b8
  grant-type: authorization_code
  redirect-url: http://www.shiyit.com/callback/gitee
  access-token-url: https://gitee.com/oauth/token
  user-info-url: https://gitee.com/api/v5/user?access_token={access_token}

baidu:
    url: http://data.zz.baidu.com/urls?site=www.shiyit.com&token=aw5iVpNEB9aQJOYZ